ignoredBuiltDependencies:
  - unrs-resolver

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@ktam/*'
  # Renovate security update: pnpm@10.28.2
  - pnpm@10.28.2

publishBranch: main

savePrefix: ''

saveWorkspaceProtocol: rolling
