ignoredBuiltDependencies:
  - esbuild
  - unrs-resolver

minimumReleaseAge: 2880 # 2 days

minimumReleaseAgeExclude:
  - '@ktam/*'
  # Renovate security update: vitest@4.1.11
  - vitest@4.1.11

publishBranch: main

savePrefix: ''

saveWorkspaceProtocol: rolling
