ignoredBuiltDependencies:
  - esbuild
  - unrs-resolver

minimumReleaseAge: 2880 # 2 days

minimumReleaseAgeExclude:
  - '@ktam/*'
  # Renovate security update: pnpm@10.34.5
  - pnpm@10.34.5

publishBranch: main

savePrefix: ''

saveWorkspaceProtocol: rolling
